### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by RobinBarnwell** [Algo-Web/POData#99]
Please could I ask if this will allow me to expose a MySQL database as an OData service working for a PHP CMS e.g. Wordpress or Drupal?

If so, please could you let me know the installation and set-up instructions.  I'm looking to integrate with Salesforce.

**Comment by CyberiaResurrection** [comment]
Hi @RobinBarnwell,

Short answer, yes, it will allow you to expose your MySQL database over OData (v3 at moment for us).  Integration and hookup will be somewhat involved.  POData is a Composer package, so that will constrain your approach a bit.

Long answer, 
To ensure I understand correctly, you're wanting to have the PHP CMS exposing an OData endpoint and then have Salesforce act as the client?

I've never hacked on Wordpress or administered an install, and haven't hacked on Drupal in the past three years, so my PHP CMS knowledge is shaky at best.  I won't be able to give you specific instructions that worth even as much as the electrons carrying them, so I won't bother.

A quick survey (probably less than you've already done) reveals some moribund adaptors/plugins for both Drupal and WP, but they're read-only and haven't been updated since 2014.

I don't know of an existing POData adapter for either of those two packages - I am very happy to be proved wrong here.

Your major tasks would then become (for example, as we've done in POData-Laravel):
1 - Generating metadata for each DB table you're wanting to expose.  If you're using an ORM of some sort, this should be easier than laying over bare DB tables.
2 - Adding the inter-table relationships you want to expose.  See 1, regarding ORM use.
3 - Implement some way of routing requests from POData into your CMS, and the responses back out again.
4 - Implement a database adaptor between POData and your CMS.

Classes to look at extending/modifying would be:
SImpleDataService
SimpleQueryProvider
SimpleMetadataProvider
SimpleOperativeContext
SimpleRequestAdapter

Our fearless leader wrote those to ease our own task of writing POData-Laravel, so they should also get you out of strife and under way.

**Comment by RobinBarnwell** [comment]
Thank you very much for the swift and detailed reply.  I'm not a web programmer so am a little lost as I do Salesforce.  I've found this which offers a free oData connection to a MySQL database:  https://skyvia.com/

I'm going to start with this as it's just configuration not coding and get more complex if it does not work.  Many thanks for your support, Robin

**Comment by CyberiaResurrection** [comment]
No problem, @RobinBarnwell , that sounds like a very good idea - start simple, then add as needed.
